/*
* This code is automatically generated by the schemaGenerator.js
* Please avoid to modify it manually, instead use the gulp task
* stored in AskiaScriptEditor project
*/
CodeMirror.xsdSchemas = CodeMirror.xsdSchemas || {};
CodeMirror.xsdSchemas["http://www.askia.com/2.3.0/ADPSchema"] = {
  schema : {
    "root": "page",
    "tags": [
        {
            "name": "page",
            "children": [
                "info",
                "outputs",
                "properties"
            ],
            "desc": "Root node of the ADP definition.",
            "attrs": [
                {
                    "name": "version",
                    "desc": "Version number of the ADP format definition.\r\n            (Not the version of the page but the version of the ADP format)",
                    "values": [
                        {
                            "name": "2.1.0",
                            "desc": "Based version of the ADP."
                        },
                        {
                            "name": "2.2.0",
                            "desc": "Compatible with 5.5.2"
                        },
                        {
                            "name": "2.3.0",
                            "desc": "Compatible with 5.6.0"
                        }
                    ]
                },
                {
                    "name": "askiaCompat",
                    "desc": "Compatibility version with Askia product."
                }
            ]
        },
        {
            "name": "info",
            "children": [
                "guid",
                "name",
                "version",
                "date",
                "description",
                "author",
                "company",
                "site",
                "helpURL"
            ],
            "desc": "Meta-data of the ADP."
        },
        {
            "name": "guid",
            "children": [],
            "desc": "Unique identifier of the ADP.\r\n              Should be share accross version of the same ADP."
        },
        {
            "name": "name",
            "children": [],
            "desc": "User friendly name of the ADP."
        },
        {
            "name": "version",
            "children": [],
            "desc": "Version of the ADP.\r\n              This version must contains at least one digit and maximum 3 digits separates with a dot period (ex: 1, 1.0, 1.0.1).\r\n              It could also contains an extra version information such as 'alpha', 'beta' or 'rc' optionally follow by a number (ex: 1.alpha2, 1.0.beta10, 1.0.1.rc3)."
        },
        {
            "name": "date",
            "children": [],
            "desc": "Release date of the ADP."
        },
        {
            "name": "description",
            "children": [],
            "desc": "Describes the ADP."
        },
        {
            "name": "author",
            "children": [],
            "desc": "Name of the ADP author(s)."
        },
        {
            "name": "company",
            "children": [],
            "desc": "Name of the company who provide the ADP."
        },
        {
            "name": "site",
            "children": [],
            "desc": "URL to the author/company web site."
        },
        {
            "name": "helpURL",
            "children": [],
            "desc": "URL to the help file of the ADP."
        },
        {
            "name": "outputs",
            "children": [
                "output"
            ],
            "desc": "List all possible ADP's outputs.\r\n        A condition could be specify for each outputs to make it alternative.",
            "attrs": [
                {
                    "name": "defaultOutput",
                    "desc": "Indicates the id of default output to use when none of the output conditions matches.\r\n            It is require as the latest output fallback."
                }
            ]
        },
        {
            "name": "output",
            "children": [
                "description",
                "condition",
                "content"
            ],
            "desc": "Output of the ADP.",
            "attrs": [
                {
                    "name": "id",
                    "desc": "Unique identifier of the output.\r\n            It use on the defaultOutput attribute of the outputs element."
                },
                {
                    "name": "masterPage",
                    "desc": "Name of the dynamic HTML file to use as the master page.\r\n            The master page HTML file must content custom Askia Tags such as:\r\n            - &lt;askia-head /&gt;\r\n            - &lt;askia-form&gt; / &lt;askia-questions /&gt; / &lt;/askia-form&gt;\r\n            - &lt;askia-foot /&gt;"
                }
            ]
        },
        {
            "name": "description",
            "children": [],
            "desc": "Describes the element"
        },
        {
            "name": "condition",
            "children": [],
            "desc": "AskiaScript condition to use the current element."
        },
        {
            "name": "content",
            "children": [
                "yield",
                "attribute"
            ],
            "desc": "Content of the specify output.",
            "attrs": [
                {
                    "name": "fileName",
                    "desc": "File use to generate the content."
                },
                {
                    "name": "type",
                    "desc": "Indicates the type of content.\r\n            According to this type, the system will automatically generate\r\n            the proper HTML fragment unless the &lt;yield&gt; is specify.",
                    "values": [
                        {
                            "name": "flash",
                            "desc": "Flash content. Will be inserted using &lt;object /&gt; tag.\r\n                  The content must be static or share."
                        },
                        {
                            "name": "css",
                            "desc": "CSS content. Will be inserted using &lt;link href /&gt; tag when static or share\r\n                  or using the &lt;style&gt;&lt;/style&gt; tag when dynamic."
                        },
                        {
                            "name": "html",
                            "desc": "HTML content.\r\n                  Will be inserted as it is or interpreted when it's dynamic."
                        },
                        {
                            "name": "javascript",
                            "desc": "Javascript content. Will be inserted using the &lt;script src /&gt; tag when static or share\r\n                  or using &lt;script&gt;&lt;/script&gt; tag when dynamic."
                        },
                        {
                            "name": "image",
                            "desc": "Image content. Will be inserted using the &lt;img src /&gt; tag.\r\n                  The content must be static or share."
                        },
                        {
                            "name": "video",
                            "desc": "Video content. Will be inserted using the &lt;video src /&gt; tag.\r\n                  The content must be static or share."
                        },
                        {
                            "name": "audio",
                            "desc": "Audio content. Will be inserted using the &lt;audio src /&gt; tag.\r\n                  The content must be static or share."
                        },
                        {
                            "name": "binary",
                            "desc": "Arbitrary binary file.\r\n                  Will be inserted according to the specify &lt;yield&gt; tag.\r\n                  The &lt;yield&gt; should be specified using a binary content otherwize the system will not create an output."
                        },
                        {
                            "name": "text",
                            "desc": "Text-based file.\r\n                  Will be inserted as it is or interpreted when it's dynamic."
                        },
                        {
                            "name": "asx",
                            "desc": "Askia script extension file.\r\n                  The file must contain modules and exported functions. It must be in the modules directory"
                        }
                    ]
                },
                {
                    "name": "mode",
                    "desc": "Indicate how the content will be treat and where the system should find the content file.",
                    "values": [
                        {
                            "name": "share",
                            "desc": "The share content is always associated with a file and must be place in the /Resources/Share/ folder of the ADP.\r\n                  The share content will be extract in the resources folder of the survey /Resources/SurveyName/.\r\n                  This kind of content, could be share accross ADX component and will not be overrides when it already exist in the folder."
                        },
                        {
                            "name": "static",
                            "desc": "The static content is always associated with a file and must be place in the /Resources/Static/ folder of the ADP.\r\n                  The static content will be extract in the resources folder of the ADP /Resources/SurveyName/ADPname/."
                        },
                        {
                            "name": "dynamic",
                            "desc": "The dynamic content could be file (text based) or in-line code define in the definition of the content.\r\n                  It could embed AskiaScript to execute.\r\n                  When the content is a file, it must be place in the /Resources/Dynamic folder of the ADP.\r\n                  The dynamic content will not be extract but load in memory."
                        },
                        {
                            "name": "modules",
                            "desc": "The modules content is always associated with an asx file and must be place in the /Resources/Modules/ folder of the ADC or ADP..\r\n                  It could embed AskiaScript to execute.\r\n                  When the content is a file, it must be place in the /Resources/Dynamic folder of the ADC.\r\n                  The content will not be extracted physically but the compiled modules will be kept in memory."
                        }
                    ]
                },
                {
                    "name": "position",
                    "desc": "Indicates how and where the system must render the current content.",
                    "values": [
                        {
                            "name": "none",
                            "desc": "The resource will not be rendered.\r\n                  But it's still available through HTTP request."
                        },
                        {
                            "name": "head",
                            "desc": "The resource will be inserted in the &lt;askia-head /&gt; section of the master page.\r\n                  Mostly use for CSS stylesheet."
                        },
                        {
                            "name": "foot",
                            "desc": "The resource will be inserted in the &lt;askia-foot /&gt; section of the master page.\r\n                  Mostly use for javascript insertion."
                        }
                    ]
                }
            ]
        },
        {
            "name": "attribute",
            "children": [
                "value"
            ],
            "desc": "Additional attribute to add or to overwrite in the auto-generated tag.\r\n        When &lt;yield&gt; is present the attribute is not take in account.",
            "attrs": [
                {
                    "name": "name",
                    "desc": "Name of the attribute."
                }
            ]
        },
        {
            "name": "value",
            "children": [],
            "desc": "Value of the attribute.\r\n        This value could be dynamic, embed AskiaScript code."
        },
        {
            "name": "yield",
            "children": [],
            "desc": "Dynamic string which indicates how the content must be rendered.\r\n        It override the built-in HTML render by the system.\r\n        Must be use for the non-manageed file, such as binary or text"
        },
        {
            "name": "properties",
            "children": [
                "category",
                "property"
            ],
            "desc": "List of properties accessible through the user interface."
        },
        {
            "name": "category",
            "children": [
                "property"
            ],
            "desc": "Category of the properties.",
            "attrs": [
                {
                    "name": "id",
                    "desc": "Unique id of the category."
                },
                {
                    "name": "name",
                    "desc": "User friendly name of the category to show on the interface."
                },
                {
                    "name": "collapsed",
                    "desc": "Indicates if the category should be collapsed by default."
                }
            ]
        },
        {
            "name": "property",
            "children": [],
            "desc": "Property accessible through the user interface.",
            "attrs": []
        },
        {
            "name": "property",
            "children": [],
            "desc": "Property accessible through the user interface.",
            "attrs": []
        },
        {
            "name": "description",
            "children": [],
            "desc": "Describes the aim of the property."
        },
        {
            "name": "value",
            "children": [],
            "desc": "Default value of the property."
        },
        {
            "name": "value",
            "children": [],
            "desc": "Default value of the property."
        },
        {
            "name": "options",
            "children": [
                "option"
            ],
            "desc": "Enumerates all allowed values."
        },
        {
            "name": "option",
            "children": [],
            "desc": "Allowed choice.",
            "attrs": [
                {
                    "name": "value",
                    "desc": "Value of the option."
                },
                {
                    "name": "text",
                    "desc": "User friendly text of the option."
                }
            ]
        }
    ]
},
  hintSchemaInfo : {
    "!top": [
        "page"
    ],
    "page": {
        "children": [
            "info",
            "outputs",
            "properties"
        ],
        "attrs": {
            "version": [
                "2.1.0",
                "2.2.0",
                "2.3.0"
            ],
            "askiaCompat": null
        }
    },
    "info": {
        "children": [
            "guid",
            "name",
            "version",
            "date",
            "description",
            "author",
            "company",
            "site",
            "helpURL"
        ]
    },
    "guid": {
        "children": []
    },
    "name": {
        "children": []
    },
    "version": {
        "children": []
    },
    "date": {
        "children": []
    },
    "description": {
        "children": []
    },
    "author": {
        "children": []
    },
    "company": {
        "children": []
    },
    "site": {
        "children": []
    },
    "helpURL": {
        "children": []
    },
    "outputs": {
        "children": [
            "output"
        ],
        "attrs": {
            "defaultOutput": null
        }
    },
    "output": {
        "children": [
            "description",
            "condition",
            "content"
        ],
        "attrs": {
            "id": null,
            "masterPage": null
        }
    },
    "condition": {
        "children": []
    },
    "content": {
        "children": [
            "yield",
            "attribute"
        ],
        "attrs": {
            "fileName": null,
            "type": [
                "flash",
                "css",
                "html",
                "javascript",
                "image",
                "video",
                "audio",
                "binary",
                "text"
            ],
            "mode": [
                "share",
                "static",
                "dynamic"
            ],
            "position": [
                "none",
                "head",
                "foot"
            ]
        }
    },
    "attribute": {
        "children": [
            "value"
        ],
        "attrs": {
            "name": null
        }
    },
    "value": {
        "children": []
    },
    "yield": {
        "children": []
    },
    "properties": {
        "children": [
            "category",
            "property"
        ]
    },
    "category": {
        "children": [
            "property"
        ],
        "attrs": {
            "id": null,
            "name": null,
            "collapsed": null
        }
    },
    "property": {
        "children": []
    },
    "options": {
        "children": [
            "option"
        ]
    },
    "option": {
        "children": [],
        "attrs": {
            "value": null,
            "text": null
        }
    }
}
};
